python train_ddpm.py --output_dir="/home/chris/Data/Projects/OOD detection/ddpm-ood/output" --model_name=mnist --training_ids="/home/chris/Data/Projects/OOD detection/ddpm-ood/data/data_splits/MNIST_train.csv" --validation_ids="/home/chris/Data/Projects/OOD detection/ddpm-ood/data/data_splits/MNIST_val.csv"  --is_grayscale=1 --n_epochs=300 --beta_schedule=scaled_linear --beta_start=0.0015 --beta_end=0.0195

python reconstruct.py --output_dir="/home/chris/Data/Projects/OOD detection/ddpm-ood/output/mnist/base_noosy_run" --model_name=mnist --validation_ids="/home/chris/Data/Projects/OOD detection/ddpm-ood/data/data_splits/MNIST_val.csv" --in_ids="/home/chris/Data/Projects/OOD detection/ddpm-ood/data/data_splits/MNIST_test.csv" --out_ids="/home/chris/Data/Projects/OOD detection/ddpm-ood/data/data_splits/MNIST_test.csv" --is_grayscale=1 --beta_schedule=scaled_linear_beta --beta_start=0.0015 --beta_end=0.0195 --num_inference_steps=100 --inference_skip_factor=4 --run_val=1 --run_in=1 --run_out=1

python ood_detection.py --output_dir="/home/chris/Data/Projects/OOD detection/ddpm-ood/output/mnist/base_noosy_run" --model_name=mnist 

python train_ddpm.py --output_dir="/home/chris/Data/Projects/OOD detection/ddpm-ood/output" --model_name=cifar10 --training_ids="/home/chris/Data/Projects/OOD detection/ddpm-ood/data/data_splits/CIFAR10_train.csv" --validation_ids="/home/chris/Data/Projects/OOD detection/ddpm-ood/data/data_splits/CIFAR10_val.csv" --is_grayscale=0 --n_epochs=300 --beta_schedule=scaled_linear_beta --beta_start=0.0015 --beta_end=0.0195
python train_ddpm.py --output_dir="/home/chris/Data/Projects/OOD detection/ddpm-ood/output" --model_name=cifar10 --training_ids="/home/chris/Data/Projects/OOD detection/ddpm-ood/data/data_splits/CIFAR10_train.csv" --validation_ids="/home/chris/Data/Projects/OOD detection/ddpm-ood/data/data_splits/CIFAR10_val.csv" --is_grayscale=0 --n_epochs=300 --beta_schedule=scaled_linear_beta --beta_start=0.0015 --beta_end=0.0195 --batch_size 256

python reconstruct.py --output_dir="/home/chris/Data/Projects/OOD detection/ddpm-ood/output/" --model_name=cifar10 --validation_ids="/home/chris/Data/Projects/OOD detection/ddpm-ood/data/data_splits/CIFAR10_val.csv" --in_ids="/home/chris/Data/Projects/OOD detection/ddpm-ood/data/data_splits/CIFAR10_test.csv" --out_ids="/home/chris/Data/Projects/OOD detection/ddpm-ood/data/data_splits/CIFAR10_test.csv" --is_grayscale=0 --beta_schedule=scaled_linear_beta --beta_start=0.0015 --beta_end=0.0195 --num_inference_steps=100 --inference_skip_factor=4 --run_val=1 --run_in=1 --run_out=1

python ood_detection.py --output_dir="/home/chris/Data/Projects/OOD detection/ddpm-ood/output/" --model_name=cifar10 --max_t 250 --t_skip 10

python reconstruct.py --output_dir="/home/chris/Data/Projects/OOD detection/ddpm-ood/output/" --model_name=cifar10 --validation_ids="/home/chris/Data/Projects/OOD detection/ddpm-ood/data/data_splits/CIFAR10_val.csv" --in_ids="/home/chris/Data/Projects/OOD detection/ddpm-ood/data/data_splits/CIFAR10_test.csv" --out_ids="/home/chris/Data/Projects/OOD detection/ddpm-ood/data/data_splits/CIFAR10_test.csv" --is_grayscale=0 --beta_schedule=scaled_linear_beta --beta_start=0.0015 --beta_end=0.0195 --num_inference_steps=100 --inference_skip_factor=2 --run_val=1 --run_in=1 --run_out=1 --min_t 0 --max_t 250 --first_n 1000

python reconstruct.py --output_dir="/home/chris/Data/Projects/OOD detection/ddpm-ood/output/" --model_name=cifar10 --out_ids="/home/chris/Data/Projects/OOD detection/ddpm-ood/data/data_splits/CIFAR10C/CIFAR10C_test_brightness_1.csv" --is_grayscale=0 --beta_schedule=scaled_linear_beta --beta_start=0.0015 --beta_end=0.0195 --num_inference_steps=100 --inference_skip_factor=2 --run_val=0 --run_in=0 --run_out=1 --min_t 0 --max_t 250 --first_n 1000

